[project]
name = "lists"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "jinja2>=3.1.6",
    "sqlmodel>=0.0.24",
]
